const services = [
  {
    title: "Breathe into Calm",
    category: "Reduce Stress",
    affirmation: "Your breath is your anchor.",
    instruction:
      "Inhale for 4 seconds, hold for 4, exhale for 6. Repeat 3 times.",
    microTask: "Try the 4-7-8 breathing technique.",
    reflection: "How does your body feel after focusing on your breath?",
  },
  {
    title: "Shoulder Drop",
    category: "Reduce Stress",
    affirmation: "Let go of what you're holding.",
    instruction:
      "Raise your shoulders to your ears, hold, and drop them slowly while exhaling.",
    microTask: "Do a 1-minute shoulder roll stretch.",
    reflection: "What tension did you release just now?",
  },
  {
    title: "Quiet the Noise",
    category: "Reduce Stress",
    affirmation: "You are allowed to unplug.",
    instruction: "Turn off all screens for 5 minutes and sit in silence.",
    microTask: "Close your eyes and notice 3 sounds around you.",
    reflection: "What happens when you give yourself silence?",
  },
  {
    title: "Grounded in Now",
    category: "Reduce Stress",
    affirmation: "This moment is all that matters.",
    instruction:
      "Place your hands on your lap. Feel the weight of your body on the chair.",
    microTask: "Do a 2-minute grounding scan of your feet and legs.",
    reflection: "What part of you feels most grounded?",
  },
  {
    title: "Nature Pause",
    category: "Reduce Stress",
    affirmation: "Nature has a rhythm — so do you.",
    instruction:
      "Step outside or look out a window and notice 3 things in nature.",
    microTask: "Listen to 1 minute of nature sounds.",
    reflection: "What in nature feels calming to you?",
  },
  {
    title: "Soothe with Breath",
    category: "Reduce Stress",
    affirmation: "Each breath brings more peace.",
    instruction:
      "Place one hand on your belly and one on your chest. Breathe slowly and deeply.",
    microTask: "Breathe deeply while counting backward from 10.",
    reflection: "How did your breath change your stress level?",
  },
  {
    title: "The Power of Pause",
    category: "Reduce Stress",
    affirmation: "You can stop. You can rest.",
    instruction:
      "Pause what you're doing and take three slow, mindful breaths.",
    microTask: "Set a timer to take a short break every hour today.",
    reflection: "How did pausing shift your energy?",
  },
  {
    title: "Reset with Movement",
    category: "Reduce Stress",
    affirmation: "Movement creates flow within.",
    instruction: "Stand up, stretch your arms wide, and shake them gently.",
    microTask: "Do a 2-minute full body stretch.",
    reflection: "What moved through you as you moved your body?",
  },
  {
    title: "Let Go Gently",
    category: "Reduce Stress",
    affirmation: "Not everything needs to be held onto.",
    instruction: "Write down one worry and then tear it up or delete it.",
    microTask:
      "Imagine placing your worry in a balloon and letting it float away.",
    reflection: "What is one thing you’re ready to release?",
  },
  {
    title: "Heart to Hand",
    category: "Reduce Stress",
    affirmation: "Compassion starts with you.",
    instruction:
      "Place your hand over your heart and say one kind thing to yourself.",
    microTask: "Repeat a calming affirmation for 1 minute.",
    reflection: "What words did your heart need to hear today?",
  },
  {
    title: "Calm Corners",
    category: "Reduce Stress",
    affirmation: "A peaceful space can help you breathe easier.",
    instruction: "Tidy or organize a small corner of your room.",
    microTask: "Light a candle or hold a calming object.",
    reflection: "What helped create a sense of calm in your space?",
  },
  {
    title: "Sound Reset",
    category: "Reduce Stress",
    affirmation: "Healing happens in quiet and in sound.",
    instruction:
      "Play soft instrumental or ambient music. Let it wash over you.",
    microTask: "Close your eyes and listen deeply to calming music.",
    reflection: "What feeling did the music evoke?",
  },
  {
    title: "Safe and Sound",
    category: "Reduce Anxiety",
    affirmation: "You are safe in this moment.",
    instruction:
      "Place one hand on your chest and feel your breath rise and fall.",
    microTask: "Take 5 slow, deep breaths with eyes closed.",
    reflection: "What part of your body feels calmer now?",
  },
  {
    title: "Five Senses Grounding",
    category: "Reduce Anxiety",
    affirmation: "You are here, now.",
    instruction:
      "Notice 5 things you can see, 4 you can touch, 3 you can hear, 2 you can smell, 1 you can taste.",
    microTask: "Say each item aloud or write them down.",
    reflection: "Which sense helped you feel most grounded?",
  },
  {
    title: "Anxiety Body Scan",
    category: "Reduce Anxiety",
    affirmation: "Your body holds answers and calm.",
    instruction: "Close your eyes and scan your body slowly from head to toe.",
    microTask: "Breathe into any areas that feel tense.",
    reflection: "What did you notice as you scanned your body?",
  },
  {
    title: "Breathe Easy",
    category: "Reduce Anxiety",
    affirmation: "Each breath can ease the mind.",
    instruction:
      "Inhale through the nose for 4 seconds, hold for 4, exhale for 6.",
    microTask: "Repeat for 3 cycles, focusing only on the breath.",
    reflection: "How did your breath change your mind?",
  },
  {
    title: "Name It to Tame It",
    category: "Reduce Anxiety",
    affirmation: "Naming your feeling can reduce its power.",
    instruction: "Take a moment to name the emotion you're feeling.",
    microTask: "Write it down or say it out loud: 'I feel…'",
    reflection: "What happens when you give your feeling a name?",
  },
  {
    title: "Thought Catcher",
    category: "Reduce Anxiety",
    affirmation: "Not every thought is true.",
    instruction: "Notice a recurring anxious thought and gently question it.",
    microTask: "Ask yourself: Is this fact, or just fear?",
    reflection: "What’s one thought you can gently let go of?",
  },
  {
    title: "Create a Calm Space",
    category: "Reduce Anxiety",
    affirmation: "Your space can hold your peace.",
    instruction: "Choose a quiet corner or small area to sit comfortably.",
    microTask: "Light a candle or play soft nature sounds.",
    reflection: "How does this space affect your breathing or heart rate?",
  },
  {
    title: "Tension Release",
    category: "Reduce Anxiety",
    affirmation: "You can release what you’re holding.",
    instruction:
      "Tense your fists tightly for 5 seconds, then release and relax.",
    microTask: "Repeat with shoulders or legs.",
    reflection: "What did your body feel like after letting go?",
  },
  {
    title: "Affirm Your Calm",
    category: "Reduce Anxiety",
    affirmation: "I am calm, capable, and in control.",
    instruction: "Repeat this affirmation slowly 3 times.",
    microTask: "Write your own calming phrase and place it nearby.",
    reflection: "Which words resonated most with you?",
  },
  {
    title: "Cloud Watch",
    category: "Reduce Anxiety",
    affirmation: "Thoughts pass like clouds.",
    instruction: "Imagine your anxious thoughts as clouds drifting in the sky.",
    microTask: "Watch them float by without holding onto them.",
    reflection: "Which thought are you ready to let pass?",
  },
  {
    title: "Heart Rhythm",
    category: "Reduce Anxiety",
    affirmation: "Your heartbeat is your inner guide.",
    instruction: "Sit quietly and listen or feel your heartbeat.",
    microTask: "Breathe slowly and match your breath to the rhythm.",
    reflection: "What did your heartbeat tell you today?",
  },
  {
    title: "Anchor Yourself",
    category: "Reduce Anxiety",
    affirmation: "There is safety in stillness.",
    instruction: "Place both feet flat on the floor and press gently.",
    microTask: "Repeat in your mind: “I am grounded. I am here.”",
    reflection: "What sensation helped anchor you to the present?",
  },

  {
    title: "Wind Down Slowly",
    category: "Better Sleep",
    affirmation: "You deserve a peaceful rest.",
    instruction: "Turn off bright lights and put away screens.",
    microTask: "Sit or lie down in silence for 2 minutes.",
    reflection: "What thoughts are you releasing tonight?",
  },
  {
    title: "Progressive Release",
    category: "Better Sleep",
    affirmation: "Let go of the day, one muscle at a time.",
    instruction:
      "Tense each muscle group, then release it, starting from your feet to your face.",
    microTask: "Do a full body scan while breathing deeply.",
    reflection: "Which part of your body relaxed most?",
  },
  {
    title: "Evening Gratitude",
    category: "Better Sleep",
    affirmation: "Gratitude prepares the heart for rest.",
    instruction: "Write down 3 good things that happened today.",
    microTask: "Whisper 'thank you' for each one before sleeping.",
    reflection: "How did this change your mood before bed?",
  },
  {
    title: "Sleepy Breath",
    category: "Better Sleep",
    affirmation: "Calm breath invites calm dreams.",
    instruction: "Inhale for 4 seconds, hold for 7, exhale for 8.",
    microTask: "Repeat for 3–4 cycles lying in bed.",
    reflection: "How did your breath change your body?",
  },
  {
    title: "Calm the Mind",
    category: "Better Sleep",
    affirmation: "You are free to rest without solving anything.",
    instruction: "Gently tell your mind, “You can rest now.”",
    microTask:
      "Visualize placing your thoughts in a basket and setting it aside.",
    reflection: "What thought are you choosing not to carry to bed?",
  },
  {
    title: "Candle Meditation",
    category: "Better Sleep",
    affirmation: "The flicker of calm is within you.",
    instruction: "Light a candle and gaze softly at the flame for one minute.",
    microTask: "As you breathe, let your thoughts melt like wax.",
    reflection: "What quiet came to you during this moment?",
  },
  {
    title: "Warm Drink Ritual",
    category: "Better Sleep",
    affirmation: "Rituals tell the body it’s time to rest.",
    instruction: "Make a warm, non-caffeinated drink like herbal tea.",
    microTask: "Sip slowly, noticing its warmth and aroma.",
    reflection: "How does this signal sleep for you?",
  },
  {
    title: "Write and Release",
    category: "Better Sleep",
    affirmation: "Your thoughts are safe on the page.",
    instruction: "Write down any lingering worries or to-do items.",
    microTask: "Close the notebook and whisper, “Tomorrow is another day.”",
    reflection: "How did writing help clear your mind?",
  },
  {
    title: "Soothing Sounds",
    category: "Better Sleep",
    affirmation: "Soft sounds carry you to stillness.",
    instruction: "Play gentle ambient music or nature sounds at low volume.",
    microTask: "Lie down and breathe slowly as the sounds play.",
    reflection: "What sound felt most calming to you?",
  },
  {
    title: "Lavender Moment",
    category: "Better Sleep",
    affirmation: "Nature’s scents can soothe the mind.",
    instruction:
      "Apply a drop of lavender or calming oil to your pillow or wrist.",
    microTask: "Take 3 deep breaths, focusing on the scent.",
    reflection: "What memory or feeling does the scent evoke?",
  },
  {
    title: "Nighttime Affirmation",
    category: "Better Sleep",
    affirmation: "I am safe. I am still. I am ready to rest.",
    instruction: "Repeat this affirmation slowly while lying in bed.",
    microTask: "Sync the words with your breath.",
    reflection: "Which word in the affirmation felt most true?",
  },
  {
    title: "Digital Sunset",
    category: "Better Sleep",
    affirmation: "Peace grows in quiet, screen-free spaces.",
    instruction: "Turn off all screens at least 30 minutes before sleep.",
    microTask: "Dim the lights and choose a calming bedtime activity.",
    reflection: "How does unplugging help your body prepare for rest?",
  },

  {
    title: "Start with One Step",
    category: "Improve Productivity",
    affirmation: "Big progress begins with a single step.",
    instruction:
      "Write down the smallest possible task you can complete right now.",
    microTask: "Set a timer for 5 minutes and do just that task.",
    reflection: "What shifted when you broke it down?",
  },
  {
    title: "Clarity First",
    category: "Improve Productivity",
    affirmation: "Clear goals create calm action.",
    instruction: "Take a breath, then list your top 3 priorities for the day.",
    microTask: "Highlight the one that matters most and start there.",
    reflection: "What feels clearer after setting your intention?",
  },
  {
    title: "Tidy Focus",
    category: "Improve Productivity",
    affirmation: "A clear space nurtures a clear mind.",
    instruction: "Spend 2 minutes tidying your workspace.",
    microTask: "Put away or remove one distraction near you.",
    reflection: "How did your space affect your mindset?",
  },
  {
    title: "Pomodoro Moment",
    category: "Improve Productivity",
    affirmation: "Work with rhythm, not resistance.",
    instruction: "Set a 25-minute focus timer and commit to one task.",
    microTask: "Take a 5-minute break right after.",
    reflection: "How did structure help you move forward?",
  },
  {
    title: "Gentle Momentum",
    category: "Improve Productivity",
    affirmation: "You don’t have to feel ready to begin.",
    instruction: "Choose one easy task as a “starter step.”",
    microTask: "Do that one task now without judgment.",
    reflection: "How did it feel to get started?",
  },
  {
    title: "Visualize Completion",
    category: "Improve Productivity",
    affirmation: "If you can see it, you can start it.",
    instruction: "Close your eyes and imagine the task already done.",
    microTask: "Write 2 benefits of completing it.",
    reflection: "How does the end result motivate you?",
  },
  {
    title: "Time Audit",
    category: "Improve Productivity",
    affirmation: "Awareness fuels improvement.",
    instruction: "Notice how you’ve spent the last hour. Be honest, not harsh.",
    microTask: "List one change you'd like to make next hour.",
    reflection: "What pattern did you observe in your time use?",
  },
  {
    title: "Limit the List",
    category: "Improve Productivity",
    affirmation: "Focus comes from simplicity.",
    instruction: "Write down no more than 3 tasks for your next work block.",
    microTask: "Circle just one and do it with full presence.",
    reflection: "What helped you stick with just one task?",
  },
  {
    title: "Mindful Transition",
    category: "Improve Productivity",
    affirmation: "You deserve space between things.",
    instruction:
      "Before switching tasks, pause for 30 seconds and breathe deeply.",
    microTask: "Stretch your arms up, exhale slowly.",
    reflection: "How did that pause help you reset?",
  },
  {
    title: "Say No Gently",
    category: "Improve Productivity",
    affirmation: "Protecting your time is an act of self-respect.",
    instruction: "Identify one non-essential task you can release today.",
    microTask: "Remove it from your to-do list with kindness.",
    reflection: "What freed up when you said no?",
  },
  {
    title: "Fuel Your Energy",
    category: "Improve Productivity",
    affirmation: "Energy, not just time, powers productivity.",
    instruction: "Check in: are you hydrated, nourished, rested?",
    microTask: "Drink a glass of water or take a mindful snack break.",
    reflection: "How does your body’s state affect your focus?",
  },
  {
    title: "End with Intent",
    category: "Improve Productivity",
    affirmation: "A mindful wrap-up builds momentum for tomorrow.",
    instruction: "At the end of your session, list what you completed.",
    microTask: "Write down one task for tomorrow’s start.",
    reflection: "What would make tomorrow’s work feel smoother?",
  },

  {
    title: "One Thing Now",
    category: "Increase Focus",
    affirmation: "Your mind works best with one clear target.",
    instruction: "Choose one task and gently commit to just that.",
    microTask: "Turn off all other tabs, apps, or distractions for 5 minutes.",
    reflection: "What helped you stay with one thing?",
  },
  {
    title: "Mindful Start",
    category: "Increase Focus",
    affirmation: "Intentional beginnings create clarity.",
    instruction: "Before starting, take three slow breaths with eyes closed.",
    microTask: "State your intention for what you’re about to do.",
    reflection: "How did that shift your mindset?",
  },
  {
    title: "Visual Anchor",
    category: "Increase Focus",
    affirmation: "Your eyes can remind your mind to stay present.",
    instruction: "Choose a visual anchor (plant, stone, or object near you).",
    microTask: "Each time you glance at it, return to your task.",
    reflection: "What helped your attention return more gently?",
  },
  {
    title: "Focus Reset",
    category: "Increase Focus",
    affirmation: "Losing focus is natural. Returning is powerful.",
    instruction: "Set a timer for 10 minutes and begin your task.",
    microTask: "If you get distracted, simply notice and return.",
    reflection: "What did you learn about your attention habits?",
  },
  {
    title: "Breath Count",
    category: "Increase Focus",
    affirmation: "Focused breath sharpens focused thought.",
    instruction: "Count 10 breaths: inhale (1), exhale (2)... up to 10.",
    microTask: "If you lose track, gently start over.",
    reflection: "How far did you get before your mind wandered?",
  },
  {
    title: "Background Cleanse",
    category: "Increase Focus",
    affirmation: "Your environment supports your clarity.",
    instruction: "Clear one item or area in your workspace.",
    microTask: "Put away or minimize one visual distraction.",
    reflection: "How did your space influence your focus?",
  },
  {
    title: "Digital Pause",
    category: "Increase Focus",
    affirmation: "You can choose what deserves your attention.",
    instruction: "Silence or move away from your phone for 15 minutes.",
    microTask: "Notice how it feels to be unreachable for a while.",
    reflection: "What was most tempting about your phone?",
  },
  {
    title: "Music for Focus",
    category: "Increase Focus",
    affirmation: "The right sound fuels deep thought.",
    instruction: "Play instrumental or ambient music while working.",
    microTask: "Notice how sound affects your mental pace.",
    reflection: "What type of music helps you stay immersed?",
  },
  {
    title: "Body Alignment",
    category: "Increase Focus",
    affirmation: "A balanced body supports a steady mind.",
    instruction: "Sit upright, feet flat, shoulders soft, neck aligned.",
    microTask: "Hold this posture for 2 minutes while breathing deeply.",
    reflection: "How did your posture affect your clarity?",
  },
  {
    title: "Mini Break Focus Boost",
    category: "Increase Focus",
    affirmation: "Stepping back can sharpen your return.",
    instruction: "Step away from your screen for 2 minutes.",
    microTask: "Stretch your body or walk around the room.",
    reflection: "How did this movement reset your focus?",
  },
  {
    title: "Clear the Mind",
    category: "Increase Focus",
    affirmation: "A cluttered mind needs space, not pressure.",
    instruction: "Write down every thought or task on your mind (brain dump).",
    microTask: "Circle only one to start with.",
    reflection: "What freed up after writing it all down?",
  },
  {
    title: "Breathe Before the Next Task",
    category: "Increase Focus",
    affirmation: "Transition time is focus time.",
    instruction: "Before switching tasks, pause for one deep breath.",
    microTask: "Say to yourself, “Now I shift into...” and name the task.",
    reflection: "What helped you move more mindfully between tasks?",
  },
  {
    title: "You Are Not Alone",
    category: "Manage Loneliness",
    affirmation: "Loneliness is a feeling, not a fact.",
    instruction:
      "Place your hand over your heart and say: 'I am with myself right now.'",
    microTask: "Sit quietly and listen to the rhythm of your heartbeat.",
    reflection: "What does it mean to feel connected to yourself?",
  },
  {
    title: "Send a Silent Wish",
    category: "Manage Loneliness",
    affirmation: "Connection can exist without words.",
    instruction: "Think of someone you care about or miss.",
    microTask: "Close your eyes and send them a silent wish for peace or joy.",
    reflection: "How did it feel to focus on another’s well-being?",
  },
  {
    title: "Write to a Friend",
    category: "Manage Loneliness",
    affirmation: "You are still part of someone’s story.",
    instruction:
      "Write a short message to someone you haven’t talked to in a while.",
    microTask: "Even if you don’t send it, write as if they’ll read it.",
    reflection: "What did this connection stir within you?",
  },
  {
    title: "Your Inner Circle",
    category: "Manage Loneliness",
    affirmation: "You’ve mattered to others before — and you still do.",
    instruction: "List 3 people who’ve been kind to you in the past.",
    microTask: "Write what you appreciated about each one.",
    reflection:
      "What do these memories tell you about the love you’ve received?",
  },
  {
    title: "Talk to Yourself Kindly",
    category: "Manage Loneliness",
    affirmation: "You are your own closest companion.",
    instruction: "Say aloud: “I see you. I’m here for you.”",
    microTask:
      "Repeat those words while looking into a mirror or holding your hand.",
    reflection: "How did it feel to hear those words from yourself?",
  },
  {
    title: "Comfort Object Check-In",
    category: "Manage Loneliness",
    affirmation: "Familiar things can carry warmth.",
    instruction:
      "Hold or sit near something that brings comfort (a stuffed toy, photo, or book).",
    microTask: "Notice any memories or feelings it brings up.",
    reflection: "What emotions does this object connect you to?",
  },
  {
    title: "Loneliness Letter",
    category: "Manage Loneliness",
    affirmation: "Your feelings deserve to be expressed.",
    instruction: "Write a letter from your loneliness — let it speak freely.",
    microTask: "Then write a compassionate response back to it.",
    reflection: "What do you learn when you listen to loneliness?",
  },
  {
    title: "Nature Connection",
    category: "Manage Loneliness",
    affirmation: "The world is alive and present with you.",
    instruction: "Step outside or look out your window at nature.",
    microTask:
      "Watch something natural — clouds, leaves, birds — for one full minute.",
    reflection: "Did you feel part of something larger?",
  },
  {
    title: "Breathe with the World",
    category: "Manage Loneliness",
    affirmation: "We all breathe the same air.",
    instruction: "Take 5 slow, deep breaths. Imagine others doing the same.",
    microTask: "Picture yourself connected through breath with others.",
    reflection: "How does this shift your sense of isolation?",
  },
  {
    title: "Reconnect with Memory",
    category: "Manage Loneliness",
    affirmation: "You carry every moment of connection within you.",
    instruction: "Recall a time when you felt deeply connected to someone.",
    microTask: "Write down what made that moment meaningful.",
    reflection: "What does this memory remind you about who you are?",
  },
  {
    title: "Join Without Speaking",
    category: "Manage Loneliness",
    affirmation: "Presence doesn’t always need words.",
    instruction:
      "Join an online livestream, podcast, or relaxing video with others present.",
    microTask: "Let your focus rest on shared experience, not performance.",
    reflection: "What was comforting about being ‘with’ others quietly?",
  },
  {
    title: "Self-Hug Moment",
    category: "Manage Loneliness",
    affirmation: "You are never truly alone when you turn inward with love.",
    instruction: "Wrap your arms around yourself and hold gently.",
    microTask: "Close your eyes and repeat: 'I’m here. I’ve got you.'",
    reflection: "How does your body respond to being held, even by you?",
  },

  {
    title: "Inner Weather Check",
    category: "Increase Self-Awareness",
    affirmation: "Noticing your inner world is a form of wisdom.",
    instruction:
      "Pause and ask yourself: 'What’s the emotional weather inside me today?'",
    microTask: "Label the feeling—sunny, cloudy, stormy, etc.",
    reflection: "What patterns do you notice in your emotional climate?",
  },
  {
    title: "Thought Observer",
    category: "Increase Self-Awareness",
    affirmation: "You are not your thoughts—you are the one noticing them.",
    instruction:
      "For 2 minutes, simply watch your thoughts pass by like clouds.",
    microTask: "Don’t chase or change them—just observe.",
    reflection: "Which thoughts seemed to visit most often?",
  },
  {
    title: "What Energizes You?",
    category: "Increase Self-Awareness",
    affirmation: "Your joy reveals your truth.",
    instruction: "List 3 things that made you feel alive this week.",
    microTask: "Highlight the one that surprised you.",
    reflection: "What does that tell you about your needs or values?",
  },
  {
    title: "Triggers and Treasures",
    category: "Increase Self-Awareness",
    affirmation: "Every reaction has a root.",
    instruction: "Recall a recent moment you felt upset or joyful.",
    microTask: "Ask yourself: 'What triggered this feeling?'",
    reflection: "What deeper belief or memory might be connected?",
  },
  {
    title: "Mirror Moment",
    category: "Increase Self-Awareness",
    affirmation: "Looking at yourself with love opens understanding.",
    instruction: "Look at yourself in a mirror for 30 seconds with soft eyes.",
    microTask: "Say something kind or honest to yourself.",
    reflection: "What was hardest or easiest to say?",
  },
  {
    title: "Why Do I Do That?",
    category: "Increase Self-Awareness",
    affirmation: "Curiosity leads to growth.",
    instruction: "Notice one habit you’ve repeated today.",
    microTask:
      "Ask yourself: 'What am I trying to avoid or gain with this habit?'",
    reflection: "What would you like to do differently next time?",
  },
  {
    title: "Value Check-In",
    category: "Increase Self-Awareness",
    affirmation: "Living in alignment brings peace.",
    instruction: "Name 3 personal values that are important to you.",
    microTask: "Rate how well you’re living by them (1–10).",
    reflection: "What value feels most neglected or honored today?",
  },
  {
    title: "Ask Your Inner Child",
    category: "Increase Self-Awareness",
    affirmation: "The child in you still speaks.",
    instruction: "Close your eyes and imagine talking to your younger self.",
    microTask: "Ask: 'What do you need right now?'",
    reflection: "What response did your inner child give you?",
  },
  {
    title: "Emotional Journal Prompt",
    category: "Increase Self-Awareness",
    affirmation: "Writing reveals what’s hidden inside.",
    instruction:
      "Set a timer for 3 minutes and finish this sentence: 'Right now, I wish…'",
    microTask: "Let the words come without editing.",
    reflection: "What surprised you about what you wrote?",
  },
  {
    title: "Mind-Body Check",
    category: "Increase Self-Awareness",
    affirmation: "Your body holds your inner truths.",
    instruction: "Notice where in your body you feel tension or lightness.",
    microTask: "Place your hand over that area and breathe deeply.",
    reflection: "What is your body telling you today?",
  },
  {
    title: "Belief Reflection",
    category: "Increase Self-Awareness",
    affirmation: "You can choose which stories to keep.",
    instruction: "Write down one belief you have about yourself.",
    microTask: "Ask: 'Is this belief helpful or harmful?'",
    reflection: "Where did this belief come from—and do you want to keep it?",
  },
  {
    title: "Who Am I Becoming?",
    category: "Increase Self-Awareness",
    affirmation: "You are a work in progress, and that’s beautiful.",
    instruction: "Visualize your future self one year from now.",
    microTask: "Write 3 traits you want to grow into.",
    reflection:
      "What small step can you take today to move toward that vision?",
  },

  {
    title: "Pause the Flame",
    category: "Manage Anger",
    affirmation: "You are allowed to pause before reacting.",
    instruction: "Close your eyes and take three deep, slow breaths.",
    microTask:
      "Inhale deeply through your nose, exhale slowly through your mouth.",
    reflection: "What changed after giving yourself a pause?",
  },
  {
    title: "Name It Gently",
    category: "Manage Anger",
    affirmation: "Naming your anger can begin to soften it.",
    instruction:
      "Say or write: “I feel angry because…” and complete the sentence.",
    microTask: "Acknowledge the feeling without judging yourself.",
    reflection: "What happens when you allow the anger to be seen?",
  },
  {
    title: "Cool Down Breath",
    category: "Manage Anger",
    affirmation: "Cool breath calms hot emotions.",
    instruction:
      "Inhale through your mouth like sipping through a straw, exhale through your nose.",
    microTask: "Do this for 1–2 minutes.",
    reflection: "How did your body respond to this breath?",
  },
  {
    title: "The Ground Beneath You",
    category: "Manage Anger",
    affirmation: "You are rooted, even in strong emotions.",
    instruction:
      "Place both feet on the floor and press them gently into the ground.",
    microTask: "Say to yourself: “I am here. I am grounded.”",
    reflection: "Did you feel more stable after grounding yourself?",
  },
  {
    title: "Shake It Out",
    category: "Manage Anger",
    affirmation: "Energy in motion is emotion released.",
    instruction: "Stand up and gently shake your arms, shoulders, and legs.",
    microTask: "Keep shaking for 1 minute, then stop and breathe.",
    reflection: "How did movement help shift your energy?",
  },
  {
    title: "Scribble It Out",
    category: "Manage Anger",
    affirmation: "There are safe ways to express anger.",
    instruction:
      "Grab a piece of paper and scribble fast and messy for 30 seconds.",
    microTask: "Crumple or tear the paper and discard it.",
    reflection: "What did that release feel like in your body?",
  },
  {
    title: "Speak to the Mirror",
    category: "Manage Anger",
    affirmation: "You can listen to yourself with compassion.",
    instruction: "Stand in front of a mirror and gently express how you feel.",
    microTask: "Say: “I’m feeling… and it’s okay to feel this way.”",
    reflection: "How did it feel to hear your own voice with honesty?",
  },
  {
    title: "Write, Don’t React",
    category: "Manage Anger",
    affirmation: "Writing brings space between feeling and action.",
    instruction:
      "Write an unsent letter to the person or situation that upset you.",
    microTask: "Don't edit — just let it flow.",
    reflection: "What shifted after writing it all out?",
  },
  {
    title: "Count and Cool",
    category: "Manage Anger",
    affirmation: "Time helps anger transform.",
    instruction: "Slowly count backward from 20 to 1.",
    microTask: "With each number, imagine cooling a flame inside you.",
    reflection: "How far did the heat of your anger drop?",
  },
  {
    title: "Soften the Hands",
    category: "Manage Anger",
    affirmation: "Softness can exist even in tension.",
    instruction:
      "Clench your fists tightly for 5 seconds, then release and open them.",
    microTask: "Repeat 2–3 times with deep breaths.",
    reflection: "How does your body react when you let go?",
  },
  {
    title: "Visualize Calm",
    category: "Manage Anger",
    affirmation: "You can create calm within you.",
    instruction:
      "Close your eyes and imagine a calming place (like a river, beach, or forest).",
    microTask: "Spend 1 minute mentally “walking” through this place.",
    reflection: "What image or feeling brought you peace?",
  },
  {
    title: "Anger is a Messenger",
    category: "Manage Anger",
    affirmation: "Behind anger is a need asking to be seen.",
    instruction: "Ask yourself: “What am I truly needing right now?”",
    microTask: "Write down the answer — no judgment.",
    reflection: "What is your anger trying to protect or communicate?",
  },

  {
    title: "Take One Step",
    category: "Manage Depression",
    affirmation: "Small steps count. You’ve already taken one.",
    instruction:
      "Choose the next simplest thing you can do—no matter how small.",
    microTask: "Stand up, stretch your arms, or drink a glass of water.",
    reflection: "What’s one small thing you were able to do today?",
  },
  {
    title: "You Are Not Alone",
    category: "Manage Depression",
    affirmation: "Even in darkness, connection exists.",
    instruction: "Think of someone you trust or someone who has helped you.",
    microTask: "Send a message, or simply imagine talking to them.",
    reflection: "What would you want someone to say to you right now?",
  },
  {
    title: "Feel to Heal",
    category: "Manage Depression",
    affirmation: "Your emotions are valid and worthy of space.",
    instruction: "Acknowledge how you're feeling—without judging it.",
    microTask: "Say or write: “Right now, I feel…” and finish the sentence.",
    reflection: "What did naming your feeling do for your heart?",
  },
  {
    title: "Breathe Through It",
    category: "Manage Depression",
    affirmation: "Your breath can bring you back to now.",
    instruction: "Place a hand on your belly and take 3 deep breaths.",
    microTask: "Focus only on the rise and fall of your breath.",
    reflection: "How did your breath affect your tension?",
  },
  {
    title: "Compassion Check-In",
    category: "Manage Depression",
    affirmation: "You’re doing the best you can with what you have.",
    instruction:
      "Place your hand over your heart and say something kind to yourself.",
    microTask: "Write down one thing you forgive yourself for today.",
    reflection: "What does self-compassion feel like in your body?",
  },
  {
    title: "Morning Light",
    category: "Manage Depression",
    affirmation: "Light can awaken hope.",
    instruction:
      "Open a window or step outside into the sunlight for 2–5 minutes.",
    microTask: "Feel the air on your skin and name one thing you see.",
    reflection: "How did it feel to connect with natural light?",
  },
  {
    title: "Mood Journal",
    category: "Manage Depression",
    affirmation: "Writing can lighten the weight you carry.",
    instruction:
      "Set a timer for 3 minutes and write anything that comes to mind.",
    microTask: "Let it be raw, messy, or simple. Just let it out.",
    reflection: "How did it feel to give your thoughts a space?",
  },
  {
    title: "Small Joy Search",
    category: "Manage Depression",
    affirmation: "Joy exists, even if it’s quiet.",
    instruction:
      "Look around and find one thing that brings a flicker of ease or joy.",
    microTask: "Name it, hold it, or smile at it.",
    reflection: "What small joy did you notice today?",
  },
  {
    title: "Move Gently",
    category: "Manage Depression",
    affirmation: "Movement can shift the mind and the mood.",
    instruction: "Stretch your arms overhead and gently sway side to side.",
    microTask: "Do this for 1–2 minutes while breathing slowly.",
    reflection: "What did your body need most right now?",
  },
  {
    title: "Create a Comfort Corner",
    category: "Manage Depression",
    affirmation: "You deserve comfort and care.",
    instruction:
      "Gather one cozy thing (like a blanket or pillow) and sit with it.",
    microTask: "Wrap yourself gently and breathe in comfort.",
    reflection: "How does comfort feel in this moment?",
  },
  {
    title: "Limit the Spiral",
    category: "Manage Depression",
    affirmation: "You are more than your darkest thought.",
    instruction:
      "Notice if you’re ruminating. Say gently: “I choose another thought.”",
    microTask: "Repeat a simple calming phrase like “This moment is enough.”",
    reflection: "What helped interrupt the cycle?",
  },
  {
    title: "Tomorrow Exists",
    category: "Manage Depression",
    affirmation: "Today isn’t forever.",
    instruction: "Say to yourself, “Tomorrow is a new chance.”",
    microTask: "Write one thing you’d like to try tomorrow, even if tiny.",
    reflection: "What hope, however small, can you carry into tomorrow?",
  },

  {
    title: "Smile Within",
    category: "Increase Happiness",
    affirmation: "Joy begins from the inside out.",
    instruction: "Sit comfortably and gently smile for 30 seconds.",
    microTask: "Notice how your face and mood shift as you smile.",
    reflection: "What did that smile stir within you?",
  },
  {
    title: "Gratitude Pause",
    category: "Increase Happiness",
    affirmation: "Gratitude is the root of joy.",
    instruction: "Write down 3 things you’re grateful for right now.",
    microTask: "Speak them out loud with a warm tone.",
    reflection: "How did gratitude shift your emotional state?",
  },
  {
    title: "Simple Pleasures",
    category: "Increase Happiness",
    affirmation: "Joy lives in ordinary moments.",
    instruction: "Pause and find one small thing that delights you.",
    microTask: "Take a photo of it or savor it mindfully.",
    reflection: "What made that moment feel special?",
  },
  {
    title: "Joyful Movement",
    category: "Increase Happiness",
    affirmation: "Movement can lift your spirit.",
    instruction: "Put on your favorite upbeat song.",
    microTask: "Dance freely for 1-2 minutes.",
    reflection: "How did it feel to move with joy?",
  },
  {
    title: "Laughter Lift",
    category: "Increase Happiness",
    affirmation: "Laughter is medicine for the soul.",
    instruction: "Watch or recall something that made you laugh recently.",
    microTask: "Let yourself laugh—even if it’s forced at first.",
    reflection: "What made you laugh today?",
  },
  {
    title: "Happy Memory",
    category: "Increase Happiness",
    affirmation: "You carry joy in your memories.",
    instruction: "Close your eyes and recall a truly happy moment.",
    microTask: "Write or voice record a short description of that memory.",
    reflection: "What does that memory remind you about yourself?",
  },
  {
    title: "Share the Joy",
    category: "Increase Happiness",
    affirmation: "Happiness grows when shared.",
    instruction: "Think of someone who brings you joy.",
    microTask: "Send them a message of appreciation.",
    reflection: "How did giving joy affect your mood?",
  },
  {
    title: "Celebrate You",
    category: "Increase Happiness",
    affirmation: "You are worthy of your own celebration.",
    instruction: "List 3 things you like about yourself today.",
    microTask: "Say each one aloud as if telling a friend.",
    reflection: "Which one felt most true or surprising?",
  },
  {
    title: "Joy Jar",
    category: "Increase Happiness",
    affirmation: "You can collect moments of happiness.",
    instruction: "Write a joyful thought or moment on a small note.",
    microTask: "Add it to a jar, box, or digital journal.",
    reflection: "How does it feel to save happiness for later?",
  },
  {
    title: "Kindness Ripple",
    category: "Increase Happiness",
    affirmation: "Being kind creates a joyful chain reaction.",
    instruction: "Do one small kind act anonymously today.",
    microTask: "Open a door, compliment someone, or help quietly.",
    reflection: "What joy came from your act of kindness?",
  },
  {
    title: "Nature Joy",
    category: "Increase Happiness",
    affirmation: "Nature’s beauty invites your joy.",
    instruction: "Look outside and find something beautiful in nature.",
    microTask: "Take a slow breath while observing it mindfully.",
    reflection: "What beauty lifted your mood today?",
  },
  {
    title: "Joyful Intention",
    category: "Increase Happiness",
    affirmation: "Intention shapes experience.",
    instruction:
      "Before starting your next activity, say: 'I choose joy in this moment.'",
    microTask: "Write this affirmation and place it near your workspace.",
    reflection: "How did that intention shift your approach?",
  },
  {
    title: "Step into Growth",
    category: "Personal Growth",
    affirmation: "Every step forward is worth celebrating.",
    instruction: "Write down one recent thing you learned about yourself.",
    microTask: "Reflect on a past challenge and how you overcame it.",
    reflection: "What does growth mean to you today?",
  },
  {
    title: "Own Your Journey",
    category: "Personal Growth",
    affirmation: "Your story is unfolding exactly as it should.",
    instruction:
      "Recall a time you felt proud of yourself. Sit with that feeling for a minute.",
    microTask: "Write a short message to your future self.",
    reflection: "What lesson from the past is guiding you now?",
  },
  {
    title: "Be Your Next Self",
    category: "Personal Growth",
    affirmation: "You already carry the seeds of who you’re becoming.",
    instruction: "Visualize the version of you one year from now.",
    microTask: "Write 3 qualities you want to nurture more.",
    reflection: "What’s one small way you can move toward that version today?",
  },
  {
    title: "Celebrate a Win",
    category: "Personal Growth",
    affirmation: "You deserve to be proud of your progress.",
    instruction: "Think of one thing you accomplished this week, big or small.",
    microTask: "Give yourself a reward or compliment.",
    reflection: "What helped you make that progress?",
  },
  {
    title: "Check In with You",
    category: "Personal Growth",
    affirmation: "Growth begins with awareness.",
    instruction: "Take a quiet moment and scan how you’re feeling emotionally.",
    microTask: "Write down one thing you’re avoiding and why.",
    reflection: "What is one courageous step you could take today?",
  },
  {
    title: "Plant the Seed",
    category: "Personal Growth",
    affirmation: "The smallest steps can grow the strongest roots.",
    instruction: "Choose one new thing to try this week.",
    microTask: "Schedule time to take the first step.",
    reflection: "What might open up for you if you take that step?",
  },
  {
    title: "Shift the Lens",
    category: "Personal Growth",
    affirmation: "You can choose how you see your world.",
    instruction: "Reframe a recent struggle as a growth opportunity.",
    microTask: "Write down a new perspective on a hard situation.",
    reflection: "How has your thinking evolved?",
  },
  {
    title: "Voice Your Value",
    category: "Personal Growth",
    affirmation: "You bring something beautiful to this world.",
    instruction: "List 3 strengths or values that define you.",
    microTask: "Say them out loud with confidence.",
    reflection: "How can you live more in alignment with them today?",
  },
  {
    title: "Dream It Forward",
    category: "Personal Growth",
    affirmation: "Your dreams are valid and valuable.",
    instruction: "Close your eyes and envision your dream life for 60 seconds.",
    microTask: "Sketch or journal your vision freely.",
    reflection: "What’s the first tiny step toward this dream?",
  },
  {
    title: "Grow Through Kindness",
    category: "Personal Growth",
    affirmation: "Self-growth includes how you treat others.",
    instruction: "Do one kind thing for someone today.",
    microTask: "Text or message someone a compliment.",
    reflection: "How does giving kindness help you grow?",
  },
  {
    title: "Revisit Your Why",
    category: "Personal Growth",
    affirmation: "Purpose brings clarity to your growth.",
    instruction: "Think about why your goals matter to you.",
    microTask: "Write a purpose statement in one sentence.",
    reflection: "How can you act from your purpose today?",
  },
  {
    title: "Release Comparison",
    category: "Personal Growth",
    affirmation: "Your path is unique and unfolding in its time.",
    instruction: "Catch one moment of comparison today and pause it.",
    microTask: "List three ways your journey is your own.",
    reflection: "What would change if you stopped comparing?",
  },
];

export default services;
